version: "3"
services:
  mysql:
     container_name: mysql_maintenances_db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER : mysql_user
      MYSQL_DATABASE: maintenances_db